In [20]:
import numpy as np

# Custom Array

- using the array() method

In [21]:
arr = np.array( [[1,2,3,4,5], [1,2,3,4,5], [1,2,3,4,5]] )

In [22]:
arr

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [23]:
np.shape(arr)

(3, 5)

In [24]:
ones = np.ones((2,3,5) )

In [25]:
ones

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

# Ones Array

- Using the ones() method

In [26]:
ones = np.ones((2,2,3) )

In [27]:
ones

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [28]:
np.shape(ones)

(2, 2, 3)

# Full Array (i.e; Specified Array)

- Using the full() method

In [29]:
full = np.full((2,3,4), 12)

In [30]:
full

array([[[12, 12, 12, 12],
        [12, 12, 12, 12],
        [12, 12, 12, 12]],

       [[12, 12, 12, 12],
        [12, 12, 12, 12],
        [12, 12, 12, 12]]])

In [31]:
zeros = np.zeros((2,2,3))

In [32]:
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

# Random Arrays 

- Using the Random. rand() method

In [34]:

import random
samples = random.sample(range(10,50),3)

In [36]:
samples

[21, 37, 33]

# Attributes

In [37]:
import random



random = np.random.rand(2,2,3)

In [38]:
#checking the size of an Array


random.size

12

In [39]:
random.shape

(2, 2, 3)

In [40]:
random.dtype

dtype('float64')

# SCLICING (METHOD OF RETRIVAL


In [41]:
random

array([[[0.71205894, 0.85479831, 0.08083429],
        [0.66012002, 0.03585838, 0.3275794 ]],

       [[0.07230105, 0.86236104, 0.73110531],
        [0.33800462, 0.57031178, 0.93447257]]])

In [42]:
random[0] #Produce the 1st matrix

array([[0.71205894, 0.85479831, 0.08083429],
       [0.66012002, 0.03585838, 0.3275794 ]])

In [43]:
random[1] #Produce the 2nd matrix

array([[0.07230105, 0.86236104, 0.73110531],
       [0.33800462, 0.57031178, 0.93447257]])

# Mulity Sclicing

In [44]:
random[0][0:1] #Printing Information From the First Row of the 1st Matrix

array([[0.71205894, 0.85479831, 0.08083429]])

In [45]:
random[0][0:2]

array([[0.71205894, 0.85479831, 0.08083429],
       [0.66012002, 0.03585838, 0.3275794 ]])

In [46]:
random

array([[[0.71205894, 0.85479831, 0.08083429],
        [0.66012002, 0.03585838, 0.3275794 ]],

       [[0.07230105, 0.86236104, 0.73110531],
        [0.33800462, 0.57031178, 0.93447257]]])

In [47]:
random[1][1][2]

0.9344725696800513

# Reverse Slicing

In [48]:
#Slicing From Reverse

random[-1]

array([[0.07230105, 0.86236104, 0.73110531],
       [0.33800462, 0.57031178, 0.93447257]])

# MATH FUNCTIONS

- add()
- sub()
- multiply()
- divide()
- dot()

In [70]:
arr_one = np.random.rand(2,3,3) # Generate an array of 10 random numbers between 0 and 1


arr_two = np.random.rand(2,3,3)


arr_one_as_int = (arr_one * 100).astype(int) 

print(arr_one_as_int)


[[[92 86 71]
  [ 8 98 37]
  [70 88 73]]

 [[85  9 25]
  [48 57 20]
  [74 32 10]]]


In [66]:

# Multiply by 100 to get a range of integers and convert to int

arr_two_as_int = (arr_two * 100).astype(int)  
print(arr_two_as_int)


[[[ 2 71 86]
  [12 22 51]
  [45 72 35]]

 [[83 25 98]
  [30 20 43]
  [10 20 84]]]


In [71]:
arr_one_as_int * arr_two_as_int

array([[[ 184, 6106, 6106],
        [  96, 2156, 1887],
        [3150, 6336, 2555]],

       [[7055,  225, 2450],
        [1440, 1140,  860],
        [ 740,  640,  840]]])

In [72]:
arr_one_as_int + arr_two_as_int

array([[[ 94, 157, 157],
        [ 20, 120,  88],
        [115, 160, 108]],

       [[168,  34, 123],
        [ 78,  77,  63],
        [ 84,  52,  94]]])

In [73]:
arr_one_as_int - arr_two_as_int

array([[[ 90,  15, -15],
        [ -4,  76, -14],
        [ 25,  16,  38]],

       [[  2, -16, -73],
        [ 18,  37, -23],
        [ 64,  12, -74]]])

In [74]:
arr_one_as_int // arr_two_as_int

array([[[46,  1,  0],
        [ 0,  4,  0],
        [ 1,  1,  2]],

       [[ 1,  0,  0],
        [ 1,  2,  0],
        [ 7,  1,  0]]])

In [75]:
np.dot(arr_one_as_int, arr_two_as_int)

array([[[[ 4411, 13536, 14783],
         [10926,  5440, 18678]],

        [[ 2857,  5388,  6981],
         [ 3974,  2900,  8106]],

        [[ 4481, 12162, 13063],
         [ 9180,  4970, 16776]]],


       [[[ 1403,  8033,  8644],
         [ 7575,  2805, 10817]],

        [[ 1680,  6102,  7735],
         [ 5894,  2740,  8835]],

        [[  982,  6678,  8346],
         [ 7202,  2690,  9468]]]])

# Statistics Functions

- SAMPLEE

- sqrt()
- ABs()
- Power()

In [76]:
sqrt = np.sqrt(25)

In [77]:
sqrt

5.0

In [78]:
expo = np.exp(arr_one_as_int)

In [79]:
expo

array([[[9.01762841e+39, 2.23524660e+37, 6.83767123e+30],
        [2.98095799e+03, 3.63797095e+42, 1.17191424e+16],
        [2.51543867e+30, 1.65163625e+38, 5.05239363e+31]],

       [[8.22301271e+36, 8.10308393e+03, 7.20048993e+10],
        [7.01673591e+20, 5.68572000e+24, 4.85165195e+08],
        [1.37338298e+32, 7.89629602e+13, 2.20264658e+04]]])

In [83]:
power = np.power(5,2)

In [84]:
power

25

In [85]:
abs = np.abs(-55)

In [86]:
abs

55

In [91]:
log = np.log(103)

In [92]:
log

4.634728988229636

In [93]:
min = np.min(arr_one_as_int)

In [94]:
min

8

# Update Our ARRAy

In [103]:
#Single Layer Updates

arr_one_as_int[0][0][0] = 700

In [104]:
arr_one_as_int

array([[[700,  86,  71],
        [  8,  98,  37],
        [ 70,  88,  73]],

       [[ 85,   9,  25],
        [ 48,  57,  20],
        [ 74,  32,  10]]])

In [108]:
replace = np.insert(     arr_two_as_int, 1,3000     )

In [109]:
replace

array([   2, 3000,   71,   86,   12,   22,   51,   45,   72,   35,   83,
         25,   98,   30,   20,   43,   10,   20,   84])

In [110]:
app = np.append( arr_one_as_int, 2000, axis = None)

In [111]:
app

array([ 700,   86,   71,    8,   98,   37,   70,   88,   73,   85,    9,
         25,   48,   57,   20,   74,   32,   10, 2000])

In [113]:


arr_one_as_int.shape

(2, 3, 3)

In [116]:
new_list = [300,400,555]

In [117]:
np.insert(arr_one_as_int, 1, new_list)

array([700, 300, 400, 555,  86,  71,   8,  98,  37,  70,  88,  73,  85,
         9,  25,  48,  57,  20,  74,  32,  10])

In [120]:
np.reshape(arr_one_as_int, (1,18))

array([[700,  86,  71,   8,  98,  37,  70,  88,  73,  85,   9,  25,  48,
         57,  20,  74,  32,  10]])